apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  labels:
    app: python
spec:
  replicas: 4
  selector:
    matchLabels:
      app: python
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: sid2104/pythonimages:myfirstpush
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /
            port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
