apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
    app: demo-voting-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    name: test-app-pod
    app: demo-voting-app
