apiVersion: v1
kind: Service
metadata:
  name: nginx-server
  labels:
    app: nginx
    role: leader
    tier: backend
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: nginx
    role: leader
    tier: backend
  type: LoadBalancer